"""create_lobby_system

Revision ID: 118cb4d8edaf
Revises: 2be40900d82d
Create Date: 2026-07-29 02:37:00.824015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118cb4d8edaf'
down_revision: Union[str, Sequence[str], None] = '2be40900d82d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('win_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_win_conditions_id'), 'win_conditions', ['id'], unique=False)
    op.create_table('lobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('game_mode', sa.String(), nullable=False),
    sa.Column('map_size', sa.String(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('faction_mode', sa.Boolean(), nullable=False),
    sa.Column('faction_count', sa.Integer(), nullable=False),
    sa.Column('win_condition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobbies_creator_id'), 'lobbies', ['creator_id'], unique=False)
    op.create_index(op.f('ix_lobbies_id'), 'lobbies', ['id'], unique=False)
    op.create_table('lobby_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lobby_invites_id'), 'lobby_invites', ['id'], unique=False)
    op.create_index(op.f('ix_lobby_invites_lobby_id'), 'lobby_invites', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_lobby_invites_token'), 'lobby_invites', ['token'], unique=True)
    op.create_table('lobby_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('map_size', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_id', name='uq_lobby_map')
    )
    op.create_index(op.f('ix_lobby_maps_id'), 'lobby_maps', ['id'], unique=False)
    op.create_index(op.f('ix_lobby_maps_lobby_id'), 'lobby_maps', ['lobby_id'], unique=True)
    op.create_table('lobby_players',
    sa.Column('lobby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobbies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('lobby_id', 'user_id')
    )
    op.create_index(op.f('ix_lobby_players_lobby_id'), 'lobby_players', ['lobby_id'], unique=False)
    op.create_index(op.f('ix_lobby_players_user_id'), 'lobby_players', ['user_id'], unique=False)
    op.create_table('lobby_map_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lobby_map_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('problem_title_slug', sa.String(), nullable=False),
    sa.Column('captured_by', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('captured_submission_url', sa.String(), nullable=True),
    sa.Column('capturer_leetcode_username', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lobby_map_id'], ['lobby_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lobby_map_id', 'province_id', name='uq_lobby_map_province')
    )
    op.create_index(op.f('ix_lobby_map_provinces_captured_by'), 'lobby_map_provinces', ['captured_by'], unique=False)
    op.create_index(op.f('ix_lobby_map_provinces_id'), 'lobby_map_provinces', ['id'], unique=False)
    op.create_index(op.f('ix_lobby_map_provinces_lobby_map_id'), 'lobby_map_provinces', ['lobby_map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lobby_map_provinces_lobby_map_id'), table_name='lobby_map_provinces')
    op.drop_index(op.f('ix_lobby_map_provinces_id'), table_name='lobby_map_provinces')
    op.drop_index(op.f('ix_lobby_map_provinces_captured_by'), table_name='lobby_map_provinces')
    op.drop_table('lobby_map_provinces')
    op.drop_index(op.f('ix_lobby_players_user_id'), table_name='lobby_players')
    op.drop_index(op.f('ix_lobby_players_lobby_id'), table_name='lobby_players')
    op.drop_table('lobby_players')
    op.drop_index(op.f('ix_lobby_maps_lobby_id'), table_name='lobby_maps')
    op.drop_index(op.f('ix_lobby_maps_id'), table_name='lobby_maps')
    op.drop_table('lobby_maps')
    op.drop_index(op.f('ix_lobby_invites_token'), table_name='lobby_invites')
    op.drop_index(op.f('ix_lobby_invites_lobby_id'), table_name='lobby_invites')
    op.drop_index(op.f('ix_lobby_invites_id'), table_name='lobby_invites')
    op.drop_table('lobby_invites')
    op.drop_index(op.f('ix_lobbies_id'), table_name='lobbies')
    op.drop_index(op.f('ix_lobbies_creator_id'), table_name='lobbies')
    op.drop_table('lobbies')
    op.drop_index(op.f('ix_win_conditions_id'), table_name='win_conditions')
    op.drop_table('win_conditions')
    # ### end Alembic commands ###
