"""add_submission_fields_to_provinces

Revision ID: 4b365086b96f
Revises: e8700b0b77e9
Create Date: 2026-07-28 12:27:38.874364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b365086b96f'
down_revision: Union[str, Sequence[str], None] = 'e8700b0b77e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_map_provinces', sa.Column('captured_submission_url', sa.String(), nullable=True))
    op.add_column('weekly_map_provinces', sa.Column('capturer_leetcode_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_map_provinces', 'capturer_leetcode_username')
    op.drop_column('weekly_map_provinces', 'captured_submission_url')
    # ### end Alembic commands ###
