"""create friend invites and friendships

Revision ID: 59a938282652
Revises: 6d01276943e1
Create Date: 2026-07-25 22:20:59.860446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a938282652'
down_revision: Union[str, Sequence[str], None] = '6d01276943e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_invites_accepted_by_user_id'), 'friend_invites', ['accepted_by_user_id'], unique=False)
    op.create_index(op.f('ix_friend_invites_id'), 'friend_invites', ['id'], unique=False)
    op.create_index(op.f('ix_friend_invites_inviter_user_id'), 'friend_invites', ['inviter_user_id'], unique=False)
    op.create_index(op.f('ix_friend_invites_token'), 'friend_invites', ['token'], unique=True)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    op.create_index(op.f('ix_friendships_user_a_id'), 'friendships', ['user_a_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_b_id'), 'friendships', ['user_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_user_b_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_a_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_invites_token'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_inviter_user_id'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_id'), table_name='friend_invites')
    op.drop_index(op.f('ix_friend_invites_accepted_by_user_id'), table_name='friend_invites')
    op.drop_table('friend_invites')
    # ### end Alembic commands ###
