"""create_problem_catalog_weekly_maps_and_solved

Revision ID: e8700b0b77e9
Revises: 59a938282652
Create Date: 2026-07-28 03:21:35.256343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8700b0b77e9'
down_revision: Union[str, Sequence[str], None] = '59a938282652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frontend_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_slug', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leetcode_problems_frontend_id'), 'leetcode_problems', ['frontend_id'], unique=True)
    op.create_index(op.f('ix_leetcode_problems_id'), 'leetcode_problems', ['id'], unique=False)
    op.create_index(op.f('ix_leetcode_problems_title_slug'), 'leetcode_problems', ['title_slug'], unique=True)
    op.create_table('user_solved',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_slug', sa.String(), nullable=False),
    sa.Column('solved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_slug', name='uq_user_solved_user_slug')
    )
    op.create_index(op.f('ix_user_solved_id'), 'user_solved', ['id'], unique=False)
    op.create_index(op.f('ix_user_solved_title_slug'), 'user_solved', ['title_slug'], unique=False)
    op.create_index(op.f('ix_user_solved_user_id'), 'user_solved', ['user_id'], unique=False)
    op.create_table('weekly_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['friendship_id'], ['friendships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('friendship_id', 'week_start', name='uq_weekly_map_friendship_week')
    )
    op.create_index(op.f('ix_weekly_maps_friendship_id'), 'weekly_maps', ['friendship_id'], unique=False)
    op.create_index(op.f('ix_weekly_maps_id'), 'weekly_maps', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_maps_week_start'), 'weekly_maps', ['week_start'], unique=False)
    op.create_table('weekly_map_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_map_id', sa.Integer(), nullable=False),
    sa.Column('province_id', sa.String(), nullable=False),
    sa.Column('region_id', sa.String(), nullable=False),
    sa.Column('problem_title_slug', sa.String(), nullable=False),
    sa.Column('captured_by', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['weekly_map_id'], ['weekly_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_map_id', 'province_id', name='uq_weekly_map_province')
    )
    op.create_index(op.f('ix_weekly_map_provinces_captured_by'), 'weekly_map_provinces', ['captured_by'], unique=False)
    op.create_index(op.f('ix_weekly_map_provinces_id'), 'weekly_map_provinces', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_map_provinces_weekly_map_id'), 'weekly_map_provinces', ['weekly_map_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_map_provinces_weekly_map_id'), table_name='weekly_map_provinces')
    op.drop_index(op.f('ix_weekly_map_provinces_id'), table_name='weekly_map_provinces')
    op.drop_index(op.f('ix_weekly_map_provinces_captured_by'), table_name='weekly_map_provinces')
    op.drop_table('weekly_map_provinces')
    op.drop_index(op.f('ix_weekly_maps_week_start'), table_name='weekly_maps')
    op.drop_index(op.f('ix_weekly_maps_id'), table_name='weekly_maps')
    op.drop_index(op.f('ix_weekly_maps_friendship_id'), table_name='weekly_maps')
    op.drop_table('weekly_maps')
    op.drop_index(op.f('ix_user_solved_user_id'), table_name='user_solved')
    op.drop_index(op.f('ix_user_solved_title_slug'), table_name='user_solved')
    op.drop_index(op.f('ix_user_solved_id'), table_name='user_solved')
    op.drop_table('user_solved')
    op.drop_index(op.f('ix_leetcode_problems_title_slug'), table_name='leetcode_problems')
    op.drop_index(op.f('ix_leetcode_problems_id'), table_name='leetcode_problems')
    op.drop_index(op.f('ix_leetcode_problems_frontend_id'), table_name='leetcode_problems')
    op.drop_table('leetcode_problems')
    # ### end Alembic commands ###
